export const emailStyles = {
  body: {
    margin: 0,
    backgroundColor: "#f8f1e8",
    color: "#38241f",
    fontFamily: "Georgia, 'Times New Roman', serif",
  },
  shell: {
    margin: "0 auto",
    maxWidth: "620px",
    padding: "32px 18px",
  },
  card: {
    backgroundColor: "#fffaf4",
    border: "1px solid #e6cf9a",
    padding: "34px",
  },
  eyebrow: {
    color: "#b88a45",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "11px",
    letterSpacing: "0.22em",
    margin: "0 0 18px",
    textTransform: "uppercase" as const,
  },
  heading: {
    color: "#6f1d2a",
    fontSize: "34px",
    fontWeight: 400,
    lineHeight: 1.05,
    margin: "0 0 18px",
  },
  text: {
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "15px",
    lineHeight: 1.65,
    margin: "0 0 20px",
  },
  details: {
    borderTop: "1px solid #ead8ae",
    marginTop: "24px",
    paddingTop: "18px",
  },
  row: {
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "14px",
    lineHeight: 1.6,
    margin: "0 0 9px",
  },
  label: {
    color: "#8a6a45",
    display: "inline-block",
    fontSize: "11px",
    letterSpacing: "0.12em",
    minWidth: "112px",
    textTransform: "uppercase" as const,
  },
  button: {
    backgroundColor: "#6f1d2a",
    color: "#fffaf4",
    display: "inline-block",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "13px",
    letterSpacing: "0.12em",
    marginTop: "12px",
    padding: "13px 18px",
    textDecoration: "none",
    textTransform: "uppercase" as const,
  },
  footer: {
    color: "#8a6a45",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "12px",
    lineHeight: 1.5,
    margin: "18px 0 0",
  },
};
